name: Build omnisette-server

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build omnisette-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: SideStore/omnisette-server

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install additional rust targets
        run: |
          rustup target add aarch64-linux-android
          rustup target add arm-linux-androideabi
          rustup target add armv7-linux-androideabi
          rustup target add i686-linux-android
          rustup target add thumbv7neon-linux-androideabi
          rustup target add x86_64-linux-android

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross

      - name: Build
        run: |
          cargo build --release --target=aarch64-linux-android
          cargo build --release --target=arm-linux-androideabi
          cargo build --release --target=armv7-linux-androideabi
          cargo build --release --target=i686-linux-android
          cargo build --release --target=thumbv7neon-linux-androideabi
          cargo build --release --target=x86_64-linux-android

      - name: Move and rename binaries
        run: |
          cp target/aarch64-linux-android/release/omnisette-server target/omnisette-server-android-aarch64
          cp target/arm-linux-androideabi/release/omnisette-server target/omnisette-server-android-arm
          cp target/armv7-linux-androideabi/release/omnisette-server target/omnisette-server-android-armv7
          cp target/i686-linux-android/release/omnisette-server target/omnisette-server-android-i686
          cp target/thumbv7neon-linux-androideabi/release/omnisette-server target/omnisette-server-android-thumbv7neon
          cp target/x86_64-linux-android/release/omnisette-server target/omnisette-server-android-x86_64

      - name: Upload to new release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: target/omnisette-server-android-*
          body: |
            ## Changelog

            - TODO
